name: GraalVM Native Image builds

on:
  push:
    branches: [ "main" ]
    tags:
      - '*'
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: "'clth' on ${{ matrix.os }}-${{ matrix.arch }}"
    runs-on: ${{ matrix.label  }}
    strategy:
      matrix:
        # Note that Graal v21 builds to the current architecture, and "--target" is not functional.
        # Therefore, we try to find runners that fit our targets.
        # See: https://docs.github.com/en/actions/concepts/runners/about-github-hosted-runners#overview-of-github-hosted-runners
        # ... and follow the links to the related GitHub repositories
        include:
          - label: ubuntu-latest
            os: linux
            arch: x86_64
          - label: ubuntu-24.04-arm
            os: linux
            arch: aarch64
          - label: windows-latest
            os: windows
            arch: x86_64
          - label: macos-15-intel
            os: darwin
            arch: x86_64
          - label: macos-15
            os: darwin
            arch: arm64
    steps:
      - uses: actions/checkout@v4

      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'graalvm-community'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          native-image-job-reports: 'true'

      - name: Show properties
        run: java -XshowSettings:properties --version

      - name: "Build 'clth'"
        run: ./gradlew nativeCompile
        env:
          # Needed for Windows; not an issue for other OSes
          GRADLE_OPTS: -Djava.io.tmpdir=${{ runner.temp }}

      - name: "Test resulting 'clth' executable"
        shell: bash
        env:
          NO_COLOR: true
        run: |
          exe=$(find app/build/native/nativeCompile/ -type f)
          $exe -a app-tests/src/test/resources/clth-config.yml

      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: clth-${{ matrix.os }}-${{ matrix.arch }}
          path: app/build/native/nativeCompile/clth-*
